### PR TITLE
Use respond with json

### PR DESCRIPTION
**Pull request by marcheing**
Fixes https://github.com/mezuro/kalibro_configurations/issues/81

### CODE REVIEW

**Comment by rafamanzo** [comment]
:cake:

**Comment by diegoamc** [comment]
Controllers that also need to be reafctored:
  - [ ] [Statistics](https://github.com/mezuro/kalibro_configurations/blob/master/app/controllers/statistics_controller.rb)
  - [ ] [Information](https://github.com/mezuro/kalibro_configurations/blob/master/app/controllers/information_controller.rb). On this controller we should also remove the html support.

**Comment by marcheing** [comment]
@diegoamc Done

**Comment by diegoamc** [comment]
Great work! :clap:

**Pull request merged**
