### PR TITLE
Update setup script

### PR DESCRIPTION
**Pull request by lucasmoura**
When running bin/setup script, it was not creating the test database. That happened because when bin/rake was loading spring, spring runs by default on the development environment. In order to fix that, we have update the bin/setup script to allow it use rake directly instead of bin/rake.

Also this new version of the setup script fix the problem of creating the necessary files for the tmp dir.

This merge fixes issues #91 and #90

### CODE REVIEW

**Comment by rafamanzo** [comment]
Why have spring and rake been removed from the `bin` dir?

**Comment by lucasmoura** [comment]
Since we are not using bin/rake anymore on the setup script, we could not find other scripts that were using bin/rake and bin/spring. If we are wrong on that approach, I can revert that.

@GustavoCayres

**Comment by rafamanzo** [comment]
They are used supposed to be used by the developers. They are the entrypoint to spring and make things faster. If they do not cause harm, please leave them.

**Comment by lucasmoura** [comment]
Okay, I will revert that change

**Comment by lucasmoura** [comment]
@rafamanzo Done :)

**Pull request merged**
